import { useState, useEffect } from "react";
import {
  Code,
  Play,
  RotateCcw,
  CheckCircle,
  ArrowLeft,
  Sparkles,
  Cpu,
  Award,
  AlertCircle,
  BookOpen,
  Lightbulb,
  RefreshCw,
  Settings,
  LogOut,
  Key
} from "lucide-react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { dracula } from "@uiw/codemirror-theme-dracula";

function App() {
  // --- STATE MANAGEMENT ---

  // Tracks if the Puter.js AI SDK is loaded and ready
  const [aiReady, setAiReady] = useState(false);

  // Tracks Puter's logged-in user profile, if any
  const [puterUser, setPuterUser] = useState(null);

  // AI Service Provider Choice ("puter", "gemini", or "openai")
  const [apiProvider, setApiProvider] = useState(
    localStorage.getItem("ai_provider") || "puter"
  );

  // User custom API keys stored in state (backed up in localStorage)
  const [geminiKey, setGeminiKey] = useState(
    localStorage.getItem("gemini_api_key") || ""
  );
  const [openaiKey, setOpenaiKey] = useState(
    localStorage.getItem("openai_api_key") || ""
  );
  const [claudeKey, setClaudeKey] = useState(
    localStorage.getItem("claude_api_key") || ""
  );
  const [claudeEndpoint, setClaudeEndpoint] = useState(
    localStorage.getItem("claude_endpoint") || "https://api.anthropic.com/v1/messages"
  );

  // Control state for the settings config panel modal
  const [showSettings, setShowSettings] = useState(false);

  // Holds the parsed JSON question generated by the AI
  const [questionData, setQuestionData] = useState(null);

  // Stores the candidate's code in the editor
  const [code, setCode] = useState(
    `function solution() {\n  // Write your code here\n  \n}`
  );

  // Stores detailed evaluation feedback from the AI
  const [feedback, setFeedback] = useState("");

  // Tracks loading state for AI API requests (generation/evaluation)
  const [loading, setLoading] = useState(false);

  // Tracks whether the code is evaluated as correct
  const [solved, setSolved] = useState(false);

  // Chosen difficulty level ("Beginner", "Medium", "Intermediate")
  const [difficulty, setDifficulty] = useState("");

  // Stores error or warning messages to prompt the user
  const [warning, setWarning] = useState("");

  // --- SDK INITIALIZATION & STATE CHECKERS ---

  // Periodically check if the Puter.js SDK has been injected into the window object
  useEffect(() => {
    const checkReady = setInterval(() => {
      if (window.puter?.ai?.chat) {
        setAiReady(true);
        clearInterval(checkReady);
      }
    }, 300);
    return () => clearInterval(checkReady);
  }, []);

  // Update Puter user info if signed in once Puter API is ready
  useEffect(() => {
    if (aiReady && window.puter?.auth) {
      if (window.puter.auth.isSignedIn()) {
        window.puter.auth.getUser().then((user) => {
          setPuterUser(user);
        });
      }
    }
  }, [aiReady]);

  // --- MANUAL PUTER SIGN IN/OUT FLOWS ---
  const handlePuterSignIn = async () => {
    try {
      const user = await window.puter.auth.signIn();
      setPuterUser(user);
    } catch (err) {
      console.error("Sign in failed:", err);
    }
  };

  const handlePuterSignOut = async () => {
    try {
      window.puter.auth.signOut();
      setPuterUser(null);
    } catch (err) {
      console.error("Sign out failed:", err);
    }
  };

  // --- API PROVIDER COMPILER ---

  /**
   * Helper that abstractly handles requests to different LLM services
   * (Puter, Gemini, or OpenAI) depending on the configuration.
   */
  const callAiProvider = async (prompt) => {
    if (apiProvider === "puter") {
      if (!window.puter?.ai?.chat) {
        throw new Error("Puter SDK is still loading. Please wait a second.");
      }
      const response = await window.puter.ai.chat(prompt);
      return response?.message?.content?.[0]?.text || response;
    }

    if (apiProvider === "gemini") {
      if (!geminiKey) {
        throw new Error("Gemini API Key is missing. Click the settings gear in the top-right to configure it.");
      }
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
              responseMimeType: "application/json"
            }
          })
        }
      );
      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData?.error?.message || `Gemini API error (HTTP ${res.status})`);
      }
      const data = await res.json();
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) throw new Error("Received an empty response from Gemini.");
      return text;
    }

    if (apiProvider === "openai") {
      if (!openaiKey) {
        throw new Error("OpenAI API Key is missing. Click the settings gear in the top-right to configure it.");
      }
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${openaiKey}`
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [{ role: "user", content: prompt }],
          response_format: { type: "json_object" }
        })
      });
      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData?.error?.message || `OpenAI API error (HTTP ${res.status})`);
      }
      const data = await res.json();
      const text = data.choices?.[0]?.message?.content;
      if (!text) throw new Error("Received an empty response from OpenAI.");
      return text;
    }

    if (apiProvider === "claude") {
      if (!claudeKey) {
        throw new Error("Claude API Key is missing. Click the settings gear in the top-right to configure it.");
      }
      const endpoint = claudeEndpoint || "https://api.anthropic.com/v1/messages";
      const res = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": claudeKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({
          model: "claude-3-5-sonnet-latest",
          max_tokens: 1024,
          messages: [{ role: "user", content: prompt }]
        })
      });
      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(
          errData?.error?.message ||
          `Claude API error (HTTP ${res.status}). Note: Anthropic API blocks direct browser calls due to CORS. If this fails, consider using a proxy or a CORS-bypass/allow-origin extension.`
        );
      }
      const data = await res.json();
      const text = data.content?.[0]?.text;
      if (!text) throw new Error("Received an empty response from Claude.");
      return text;
    }

    throw new Error("Unsupported API provider selected.");
  };

  // --- INTERVIEW LOGIC ---

  // Sets the selected difficulty and clears any active warnings
  const handleDifficultySelect = (level) => {
    setDifficulty(level);
    if (warning) setWarning("");
  };

  /**
   * Generates a coding interview question using Puter/Gemini/OpenAI AI.
   * Sends a structured prompt requesting a strict JSON response.
   */
  const generateQuestion = async () => {
    const validLevels = ["Beginner", "Medium", "Intermediate", "Hard"];

    if (!validLevels.includes(difficulty)) {
      setWarning("⚠️ Please select a difficulty level before generating a question.");
      return;
    }

    setLoading(true);
    setFeedback("");
    setSolved(false);
    setQuestionData(null);
    setCode(`function solution() {\n  // Write your code here\n  \n}`);

    try {
      const prompt = `Generate a ${difficulty} level coding interview question. 
      You MUST return a JSON object with EXACTLY the following structure:
      {
        "title": "Question Title",
        "description": "Clear detailed description of the problem",
        "examples": [
          {"input": "example input description", "output": "example output description"}
        ],
        "constraints": ["constraint 1", "constraint 2"]
      }
      Return only valid JSON. Do not include any conversational intro or markdown wraps.`;

      const responseText = await callAiProvider(prompt);

      // Clean potential markdown blocks if AI ignored instructions
      const cleanJson = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
      const parsed = JSON.parse(cleanJson);

      setQuestionData(parsed);
    } catch (err) {
      console.error("Error generating question:", err);
      setFeedback(`❌ ${err.message || "Failed to generate question. Please try again."}`);
    } finally {
      setLoading(false);
    }
  };

  /**
   * Submits the user's code to the AI for grading/evaluation.
   * Compares code logic against the problem description.
   */
  const submitCode = async () => {
    if (!questionData) return;

    setLoading(true);
    setFeedback("");

    try {
      const prompt = `You are a strict technical coding interviewer.
      Problem Title: ${questionData.title}
      Problem Description: ${questionData.description}
      Constraints: ${questionData.constraints?.join(", ") || "None"}
      
      Candidate's Submitted Code:
      \`\`\`javascript
      ${code}
      \`\`\`
      
      Evaluate the candidate's solution for correctness and edge cases.
      You MUST return a JSON object with EXACTLY the following structure:
      {
        "correct": true or false,
        "feedback": "A concise paragraph reviewing the logic and approach",
        "suggestions": ["improvement tip 1", "improvement tip 2"]
      }
      Return only valid JSON. Do not write any other text.`;

      const responseText = await callAiProvider(prompt);
      const cleanJson = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
      const result = JSON.parse(cleanJson);

      setSolved(result.correct);

      const suggestionsText = result.suggestions?.length
        ? `\n\n💡 Key Suggestions:\n• ${result.suggestions.join("\n• ")}`
        : "";
      setFeedback(
        `${result.correct ? "🎉 Success! Correct Solution" : "❌ Logic issues found"}\n\n${result.feedback}${suggestionsText}`
      );
    } catch (err) {
      console.error("Evaluation error:", err);
      setFeedback(`❌ ${err.message || "Failed to evaluate code. Please verify setup and try again."}`);
    } finally {
      setLoading(false);
    }
  };

  // Resets the application state back to the difficulty selection screen
  const reset = () => {
    setQuestionData(null);
    setCode(`function solution() {\n  // Write your code here\n  \n}`);
    setFeedback("");
    setSolved(false);
    setDifficulty("");
    setWarning("");
  };

  // --- RENDER COMPONENT ---
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-emerald-500 selection:text-slate-950 relative overflow-hidden">

      {/* Dynamic Background Gradient Accents */}
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-emerald-500/10 blur-[120px] rounded-full pointer-events-none"></div>
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-sky-500/10 blur-[120px] rounded-full pointer-events-none"></div>

      {/* Top Navbar Header */}
      <header className="border-b border-slate-800 bg-slate-900/60 backdrop-blur-md sticky top-0 z-50 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-tr from-emerald-500 to-teal-400 p-2 rounded-xl text-slate-950 shadow-lg shadow-emerald-500/20">
            <Cpu size={24} />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
              AI Interview Coach
              <span className="text-xs font-normal text-emerald-400 px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20">v1.2</span>
            </h1>
            <p className="text-xs text-slate-400">Interactive Technical Coding Practice</p>
          </div>
        </div>

        {/* AI Mode and Status Indicators */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 text-xs font-medium bg-slate-800/80 px-3 py-1.5 rounded-full border border-slate-700">
            <span className={`w-2 h-2 rounded-full ${apiProvider === "puter"
              ? (aiReady ? "bg-emerald-400 animate-pulse" : "bg-yellow-400")
              : "bg-sky-400 animate-pulse"
              }`} />
            <span className="text-slate-300">
              {apiProvider === "puter"
                ? (puterUser ? `Puter: ${puterUser.username}` : (aiReady ? "Puter AI Connected" : "Initializing AI SDK..."))
                : `${apiProvider.charAt(0).toUpperCase() + apiProvider.slice(1)} Mode`
              }
            </span>
          </div>

          {/* Settings Control Button */}
          <button
            onClick={() => setShowSettings(!showSettings)}
            className="p-2 rounded-lg bg-slate-800 border border-slate-750 hover:bg-slate-750 text-slate-300 hover:text-white transition cursor-pointer"
            title="Settings (API Keys)"
          >
            <Settings size={18} />
          </button>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 w-full max-w-7xl mx-auto p-4 md:p-6 lg:p-8 flex flex-col justify-center relative z-10">

        {!questionData ? (
          /* --- SELECTION SCREEN --- */
          <div className="max-w-2xl mx-auto w-full">
            <div className="text-center mb-8">
              <h2 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-teal-300 to-sky-400 tracking-tight mb-3">
                Master Your Coding Interviews
              </h2>
              <p className="text-slate-400 text-lg max-w-lg mx-auto">
                Select a difficulty level and generate fresh algorithmic challenges designed to grill your technical skills.
              </p>
            </div>

            {/* Glassmorphic Options Card */}
            <div className="bg-slate-900/40 border border-slate-800 backdrop-blur-lg rounded-2xl p-8 shadow-2xl flex flex-col gap-8">
              <div className="flex flex-col gap-3">
                <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 text-center">
                  Choose Difficulty
                </span>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  {["Beginner", "Medium", "Intermediate", "Hard"].map((level) => {
                    const isSelected = difficulty === level;
                    return (
                      <button
                        key={level}
                        onClick={() => handleDifficultySelect(level)}
                        className={`relative py-4 px-3 rounded-xl font-semibold transition-all duration-300 flex flex-col items-center justify-center gap-2 border text-sm ${isSelected
                          ? "bg-emerald-500/10 border-emerald-400 text-emerald-300 shadow-md shadow-emerald-500/5"
                          : "bg-slate-800/30 border-slate-800 text-slate-400 hover:border-slate-700 hover:bg-slate-800/50 hover:text-slate-200"
                          }`}
                      >
                        <Award size={18} className={isSelected ? "text-emerald-400" : "text-slate-500"} />
                        {level}
                        {isSelected && (
                          <span className="absolute -top-1 -right-1 w-3 h-3 bg-emerald-400 rounded-full border-2 border-slate-900" />
                        )}
                      </button>
                    );
                  })}
                </div>
              </div>

              {warning && (
                <div className="flex items-center gap-2 text-yellow-500 bg-yellow-500/10 border border-yellow-500/20 px-4 py-3 rounded-xl text-sm justify-center">
                  <AlertCircle size={16} />
                  <span>{warning}</span>
                </div>
              )}

              {/* Generate Action Button */}
              <button
                onClick={generateQuestion}
                disabled={loading || (apiProvider === "puter" && !aiReady)}
                className="w-full py-4 bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 disabled:opacity-40 disabled:pointer-events-none text-slate-950 font-bold rounded-xl shadow-lg shadow-emerald-500/10 transition duration-300 flex items-center justify-center gap-2 text-base cursor-pointer"
              >
                {loading ? (
                  <>
                    <RefreshCw size={20} className="animate-spin" />
                    Generating Challenge...
                  </>
                ) : (
                  <>
                    <Sparkles size={20} />
                    Generate Coding Question
                  </>
                )}
              </button>
            </div>
          </div>
        ) : (
          /* --- WORKSPACE SCREEN --- */
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-stretch">

            {/* Left Side: Question Display */}
            <div className="flex flex-col gap-6">
              <div className="bg-slate-900/40 border border-slate-800 backdrop-blur-lg rounded-2xl p-6 shadow-xl flex flex-col gap-6 h-full">

                {/* Back button & Tag */}
                <div className="flex items-center justify-between pb-4 border-b border-slate-800/80">
                  <button
                    onClick={reset}
                    className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-100 transition-colors"
                  >
                    <ArrowLeft size={14} /> Back to Selection
                  </button>
                  <span className="text-[10px] font-bold tracking-widest uppercase bg-emerald-500/10 text-emerald-400 px-3 py-1 rounded-full border border-emerald-500/20">
                    {difficulty}
                  </span>
                </div>

                {/* Problem details */}
                <div className="flex flex-col gap-2">
                  <h3 className="text-2xl font-bold text-white flex items-center gap-2">
                    <BookOpen size={20} className="text-emerald-400" />
                    {questionData.title}
                  </h3>
                  <p className="text-slate-300 text-sm leading-relaxed whitespace-pre-line">
                    {questionData.description}
                  </p>
                </div>

                {/* Examples */}
                {questionData.examples?.length > 0 && (
                  <div className="flex flex-col gap-3">
                    <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
                      Examples
                    </h4>
                    <div className="flex flex-col gap-2">
                      {questionData.examples.map((ex, i) => (
                        <div
                          key={i}
                          className="bg-slate-950/60 border border-slate-850 rounded-xl p-4 text-xs font-mono flex flex-col gap-1 text-slate-300"
                        >
                          <div>
                            <span className="text-emerald-400 font-semibold">Input:</span> {ex.input}
                          </div>
                          <div>
                            <span className="text-sky-400 font-semibold">Output:</span> {ex.output}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Constraints */}
                {questionData.constraints?.length > 0 && (
                  <div className="flex flex-col gap-2 pt-2">
                    <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
                      Constraints
                    </h4>
                    <ul className="list-disc list-inside text-xs text-slate-400 space-y-1.5 pl-1">
                      {questionData.constraints.map((c, i) => (
                        <li key={i}>{c}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </div>

            {/* Right Side: Code Editor & Submission */}
            <div className="flex flex-col gap-6">

              {/* Editor wrapper */}
              <div className="bg-slate-900/40 border border-slate-800 backdrop-blur-lg rounded-2xl overflow-hidden shadow-xl flex flex-col">
                <div className="flex items-center justify-between px-4 py-3 bg-slate-900/80 border-b border-slate-800">
                  <div className="flex items-center gap-2">
                    <Code size={16} className="text-emerald-400" />
                    <span className="text-xs font-mono text-slate-300">solution.js</span>
                  </div>
                  <button
                    onClick={() => setCode(`function solution() {\n  // Write your code here\n  \n}`)}
                    className="text-[10px] text-slate-500 hover:text-slate-300 flex items-center gap-1 transition"
                  >
                    <RotateCcw size={10} /> Reset Code
                  </button>
                </div>

                {/* CodeMirror Workspace */}
                <div className="text-sm">
                  <CodeMirror
                    value={code}
                    height="550px"
                    theme={dracula}
                    extensions={[javascript()]}
                    onChange={(val) => setCode(val)}
                  />
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-3">
                <button
                  onClick={submitCode}
                  disabled={loading}
                  className="flex-1 py-4 bg-emerald-500 hover:bg-emerald-400 disabled:opacity-40 text-slate-950 font-bold rounded-xl shadow-lg transition duration-300 flex items-center justify-center gap-2 text-sm cursor-pointer"
                >
                  {loading ? (
                    <>
                      <RefreshCw size={18} className="animate-spin" />
                      Evaluating Solution...
                    </>
                  ) : (
                    <>
                      <CheckCircle size={18} /> Submit Solution
                    </>
                  )}
                </button>

                <button
                  onClick={reset}
                  className="px-6 py-4 bg-slate-900 border border-slate-800 hover:bg-slate-800 text-slate-200 hover:text-white font-semibold rounded-xl transition duration-300 flex items-center gap-2 text-sm cursor-pointer"
                >
                  <RotateCcw size={18} /> New Question
                </button>
              </div>

              {/* Feedback Terminal Container */}
              {feedback && (
                <div
                  className={`rounded-2xl p-5 border shadow-xl flex flex-col gap-3 transition-all duration-300 ${solved
                    ? "bg-emerald-950/20 border-emerald-500/30 text-emerald-200"
                    : "bg-red-950/20 border-red-500/30 text-red-200"
                    }`}
                >
                  <div className="flex items-center gap-2 pb-2 border-b border-white/5 font-semibold text-sm">
                    {solved ? (
                      <CheckCircle size={16} className="text-emerald-400" />
                    ) : (
                      <AlertCircle size={16} className="text-red-400" />
                    )}
                    <span>Interviewer Evaluation Result</span>
                  </div>

                  <div className="text-xs font-mono leading-relaxed whitespace-pre-wrap">
                    {feedback}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </main>

      {/* Settings Modal Config Panel */}
      {showSettings && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 w-full max-w-md shadow-2xl relative">
            <button
              onClick={() => setShowSettings(false)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white text-lg transition font-mono cursor-pointer"
            >
              ✕
            </button>

            <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <Settings size={20} className="text-emerald-400" />
              AI Connection Settings
            </h3>

            <p className="text-xs text-slate-400 mb-5 leading-relaxed">
              If you run into low balance limits with Puter AI, you can sign in to your Puter account or input your own API key to bypass limits completely.
            </p>

            <div className="flex flex-col gap-4">
              {/* Provider Selector Options */}
              <div>
                <label className="text-xs font-semibold text-slate-300 block mb-2">AI Provider</label>
                <div className="grid grid-cols-4 gap-2">
                  {["puter", "gemini", "openai", "claude"].map((providerName) => (
                    <button
                      key={providerName}
                      onClick={() => {
                        setApiProvider(providerName);
                        localStorage.setItem("ai_provider", providerName);
                      }}
                      className={`py-2 px-1 rounded-lg text-[10px] font-semibold border transition cursor-pointer capitalize ${apiProvider === providerName
                        ? "bg-emerald-500/10 border-emerald-400 text-emerald-300"
                        : "bg-slate-800 border-slate-750 text-slate-400 hover:bg-slate-750"
                        }`}
                    >
                      {providerName === "puter" ? "Puter AI" : providerName}
                    </button>
                  ))}
                </div>
              </div>

              {/* Option-based Config Forms */}
              {apiProvider === "puter" && (
                <div className="bg-slate-950/40 p-4 rounded-xl border border-slate-800/80 flex flex-col gap-3">
                  <div className="text-xs text-slate-300">
                    {puterUser ? (
                      <div>
                        <p className="font-semibold text-emerald-400">Signed in as {puterUser.username}</p>
                        <p className="text-[10px] text-slate-500 mt-0.5">Calls will bill to your personal account.</p>
                      </div>
                    ) : (
                      <p>Currently using standard anonymous rates. Log in to access your individual free Puter credits.</p>
                    )}
                  </div>
                  {puterUser ? (
                    <button
                      onClick={handlePuterSignOut}
                      className="w-full py-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 font-semibold rounded-lg text-xs transition flex items-center justify-center gap-2 border border-red-500/20 cursor-pointer"
                    >
                      <LogOut size={12} /> Sign Out of Puter
                    </button>
                  ) : (
                    <button
                      onClick={handlePuterSignIn}
                      disabled={!aiReady}
                      className="w-full py-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold rounded-lg text-xs transition flex items-center justify-center gap-2 shadow cursor-pointer"
                    >
                      <Sparkles size={12} /> Sign In to Puter Account
                    </button>
                  )}
                </div>
              )}

              {apiProvider === "gemini" && (
                <div className="flex flex-col gap-2">
                  <label className="text-xs font-semibold text-slate-300 flex items-center justify-between">
                    <span>Gemini API Key</span>
                    <a
                      href="https://aistudio.google.com/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[10px] text-emerald-400 hover:underline flex items-center gap-0.5 font-normal"
                    >
                      <Key size={10} /> Get free API Key
                    </a>
                  </label>
                  <input
                    type="password"
                    placeholder="Paste Gemini Studio Key here..."
                    value={geminiKey}
                    onChange={(e) => {
                      setGeminiKey(e.target.value);
                      localStorage.setItem("gemini_api_key", e.target.value);
                    }}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-850 rounded-lg text-xs text-white placeholder-slate-700 focus:outline-none focus:border-emerald-500/50"
                  />
                  <p className="text-[10px] text-slate-500">
                    Runs using Google AI Studio. 15 requests per minute are completely free.
                  </p>
                </div>
              )}

              {apiProvider === "openai" && (
                <div className="flex flex-col gap-2">
                  <label className="text-xs font-semibold text-slate-300 flex items-center justify-between">
                    <span>OpenAI API Key</span>
                    <a
                      href="https://platform.openai.com/api-keys"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[10px] text-emerald-400 hover:underline flex items-center gap-0.5 font-normal"
                    >
                      <Key size={10} /> Get OpenAI Key
                    </a>
                  </label>
                  <input
                    type="password"
                    placeholder="sk-..."
                    value={openaiKey}
                    onChange={(e) => {
                      setOpenaiKey(e.target.value);
                      localStorage.setItem("openai_api_key", e.target.value);
                    }}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-850 rounded-lg text-xs text-white placeholder-slate-700 focus:outline-none focus:border-emerald-500/50"
                  />
                  <p className="text-[10px] text-slate-500">
                    Runs using gpt-4o-mini. Needs developer credits setup on OpenAI Platform.
                  </p>
                </div>
              )}

              {apiProvider === "claude" && (
                <div className="flex flex-col gap-2">
                  <label className="text-xs font-semibold text-slate-300 flex items-center justify-between">
                    <span>Claude API Key</span>
                    <a
                      href="https://console.anthropic.com/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[10px] text-emerald-400 hover:underline flex items-center gap-0.5 font-normal"
                    >
                      <Key size={10} /> Get Anthropic Key
                    </a>
                  </label>
                  <input
                    type="password"
                    placeholder="sk-ant-..."
                    value={claudeKey}
                    onChange={(e) => {
                      setClaudeKey(e.target.value);
                      localStorage.setItem("claude_api_key", e.target.value);
                    }}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-850 rounded-lg text-xs text-white placeholder-slate-700 focus:outline-none focus:border-emerald-500/50"
                  />
                  <label className="text-[10px] font-semibold text-slate-300 mt-1">
                    API Endpoint / CORS Proxy (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="https://api.anthropic.com/v1/messages"
                    value={claudeEndpoint}
                    onChange={(e) => {
                      setClaudeEndpoint(e.target.value);
                      localStorage.setItem("claude_endpoint", e.target.value);
                    }}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-850 rounded-lg text-xs text-white placeholder-slate-750 focus:outline-none focus:border-emerald-500/50 font-mono"
                  />
                  <p className="text-[10px] text-slate-500 leading-normal">
                    Uses Claude 3.5 Sonnet. Anthropic API blocks direct browser calls due to CORS. If this fails, consider using a proxy or a CORS-bypass/allow-origin extension.
                  </p>
                </div>
              )}
            </div>

            <button
              onClick={() => setShowSettings(false)}
              className="w-full mt-6 py-2.5 bg-slate-800 hover:bg-slate-750 text-white font-semibold rounded-lg text-xs transition cursor-pointer"
            >
              Close and Save
            </button>
          </div>
        </div>
      )}

      {/* Footer Info */}
      <footer className="py-6 px-6 border-t border-slate-900 bg-slate-950/40 text-center text-xs text-slate-500">
        <p className="mb-1 text-slate-400 font-semibold">Powered by Helal</p>
        <p>© 2026 AI Interview Coach. Built with React, TailwindCSS, & Puter.js SDK.</p>
      </footer>
    </div>
  );
}

export default App;
